services:
    backend_pos:
        container_name: node_pos
        build:
            context: .
            target: development
        ports:
            - '3000:3000'
        env_file:
            - .env.development
        depends_on:
            - mongo_pos
        volumes:
            - ./:/app
            - /app/node_modules

    mongo_pos:
        container_name: mongo_pos
        image: mongo:7
        ports:
            - '27017:27017' #host_post:container_port
        volumes:
            - mongo_data:/data/db
        command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

    redis_pos:
        container_name: redis_pos
        image: redis:latest
        ports:
            - '6380:6379'

volumes:
    mongo_data:

        #environment: for mongo_pos removed
        # ${MONGO_INITDB_ROOT_USERNAME}, ${MONGO_INITDB_ROOT_PASSWORD}, ${MONGO_INITDB_REPLICA_SET_NAME} should be exported first to use them in the environment variables
        #- MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        #- MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        #- MONGO_INITDB_REPLICA_SET_NAME=${MONGO_INITDB_REPLICA_SET_NAME} to initialize the replica set
